trigger: none

resources:
  repositories:
    - repository: ado-templates
      endpoint: GithubServiceConnection
      type: github
      name: larryso/ado-template
      ref: master

stages:
  - template: pipelines/stages/build-java.yml@ado-templates
    parameters:
      sonarqube_scan: true
      sourceRepositories: [self]
      sonar_service_connection: local_sonar_server
      sonar_project_key: springboot-initialization
      sonar_project_name: springboot-initialization
      working_directory: $(Agent.BuildDirectory)/s/springboot-initialization

