server:
  port: 8080

spring:
# replace this by customize ObjectMapper
#  jackson:
#    default-property-inclusion: non_null
#    date-format: java.text.SimpleDateFormat

  quartz:
    job-store-type: JDBC
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            triggerListener:
              NAME:
                class: com.larry.scheduler.quartz.listener.TigerListener
            jobListener:
              NAME:
                class: com.larry.scheduler.quartz.listener.JobListener
            scheduleListener:
              NAME:
                class: com.larry.scheduler.quartz.listener.ScheduleListener
            threadPool:
              threadCount: 10
            jobStore:
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
              isClustered: true
              clusterCheckinInterval: 20000
              maxMisfiresToHandleAtATime: 1
              misfireThreshold: 1200000
              txIsolationLevelSerializable: false
              dataSource: appDataSource
            plugin:
              jobHistory:
                class: org.quartz.plugins.history.LoggingJobHistoryPlugin
              shutdownHook:
                class: org.quartz.plugins.management.ShutdonwHookPlugin
                cleanShutdown: true

  jpa:
    database: mysql
    show-sql: false
    open-in-view: false

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-url: https://login.microsoftonline.com/e3ab21b2-a7ce-4734-96a1-36c88d566618/v2.0
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
          audience: 9b6500ba-66f3-481a-9e19-897f9ab785a1


app:
  task:
    threadNamePrefix: Async-
    poolCoreSize: 5
    poolMaxSize: 5
    queueCapacity: 100000
    batchSize: 1000
    batchChunkDelay: 100
  app-datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo
    poolName: AppHikariPool
    maximumPoolSize: 100
    minimumIdle: 10
    username: root
    password: root
  security:
    enabled: true
    oauth2.resource.nimbus-jwt-decoder:
      cache-refresh-timeout: 5m
      cache-ttl: 24h
      rate-limit-min-interval: 30s
      refresh-ahead-time: 30s
      refresh-ahead-scheduled: false
